<div class="page-title">
    <h1><?php echo __('Your Quote Request has been received') ?></h1>
</div>

<p><strong><?php echo __('Thank you for your interest!') ?></strong></p>

<?php echo __('You will receive a Quote Request confirmation email shortly.') ?>
<br />
<br />
<div class="buttons-set">
	<button class="button" type="button" onclick="window.location='<?php echo $block->getUrl('') ?>'"><span><span><?php echo __('Continue Browsing') ?></span></span></button>
</div>
